export const services = [
  {
    id: "contabilidad",
    label: "Contabilidad integral",
    title: "Gestión contable mensual",
    contactValue: "Asesoría contable",
    description: "Ordenamos compras, ventas, bancos, préstamos y cuentas para construir cierres mensuales con sustento y trazabilidad.",
    outcome: "Una contabilidad que explica lo ocurrido y prepara la siguiente decisión.",
    image: "/assets/brand/backgroundfinanzas.jpg",
    features: ["Libros contables", "Conciliación bancaria", "Análisis de cuentas", "Cierre mensual"],
  },
  {
    id: "tributaria",
    label: "Tributación",
    title: "Control tributario y SUNAT",
    contactValue: "Asesoría tributaria",
    description: "Gestionamos impuestos, PDT, SIRE y obligaciones periódicas con una revisión preventiva de los puntos críticos.",
    outcome: "Menos incertidumbre frente a vencimientos y contingencias tributarias.",
    image: "/assets/brand/backgroundfinanciero.avif",
    features: ["Liquidación de impuestos", "Presentación de PDT", "SIRE", "Revisión preventiva"],
  },
  {
    id: "laboral",
    label: "Laboral",
    title: "Planillas y obligaciones laborales",
    contactValue: "Planillas y laboral",
    description: "Administramos planillas, boletas, beneficios sociales y declaraciones laborales bajo una cadencia clara.",
    outcome: "Pagos y obligaciones laborales ordenados y previsibles.",
    image: "/assets/brand/backgroundoficina.avif",
    features: ["PLAME", "Boletas de pago", "CTS y gratificaciones", "AFP y ONP"],
  },
  {
    id: "reportes",
    label: "Finanzas",
    title: "Reportes para la gerencia",
    contactValue: "Reportes financieros",
    description: "Convertimos balances, flujos y resultados en una lectura concreta sobre caja, margen, costos y crecimiento.",
    outcome: "Información financiera que puede entenderse y utilizarse.",
    image: "/assets/brand/backgroundfinanzas.jpg",
    features: ["Estados financieros", "Flujo de efectivo", "Indicadores", "Lectura gerencial"],
  },
  {
    id: "control",
    label: "Control interno",
    title: "Revisión de procesos",
    contactValue: "Control interno",
    description: "Analizamos documentación, responsabilidades y puntos de control para detectar riesgos antes de que afecten la operación.",
    outcome: "Procesos más verificables y preparados para crecer.",
    image: "/assets/brand/backgroundoficina.avif",
    features: ["Revisión documental", "Mapa de riesgos", "Puntos de control", "Plan de mejora"],
  },
];
